// Copyright (c) 2017, 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-rest-client
:page-layout: guide
:page-duration: 20 minutes
:page-releasedate: 2018-04-20
:page-description: Learn how to use MicroProfile Rest Client to invoke RESTful services over HTTP in a type-safe way.
:page-tags: ['REST', 'MicroProfile', 'Rest Client', 'microservices']
:page-permalink: /guides/{projectid}
:page-related-guides: ['rest-intro', 'cdi-intro', 'microprofile-config']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
:source-highlighter: prettify
= Consuming RESTful services with template interfaces

Learn how to use MicroProfile Rest Client to invoke RESTful microservices over HTTP in a type-safe way.

// =================================================================================================
// What you'll learn
// =================================================================================================

== What you'll learn

You will learn how to build a MicroProfile Rest Client to access remote RESTful services.
MicroProfile Rest Client provides a type-safe way to call RESTful services so that you can focus more on the client services rather than how to connect with remote services.

The application that you will be working with is an `inventory` service, which fetches and stores the system property information for different hosts.
Whenever a request is made to retrieve the system properties of a particular host, the `inventory` service will create a client to invoke the `system`
service on that host. The `system` service simulates a remote service in the application.

You will learn how to create and register the client interface and handle exceptions through `ResponseExceptionMappers` mapper class.
Then, you will instantiate the client and use it in the `inventory` service. It is possible to do so by using two different approaches: CDI with the help of MicroProfile Config method, and the `RestClientBuilder` method.
You can choose either way to instantiate the client in the future, but in this guide you will explore both methods in order to handle different scenarios to provide a valid base URL. You must have a valid base URL to instantiate the RESTful client.

You will handle various scenarios in the following way:

 - Define the default base URL with host name as `localhost` in the configuration file, and inject the client by using the CDI method.

 - Set the base URL as a variable with the host name as a parameter, and build the RESTful client by using the `RestClientBuilder` method.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

To try out the application, first navigate to the `finish` directory, which contains the complete `inventory` application, then run the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn install liberty:start-server
```

After starting the application, you can access the following three URLs:

* The `http://localhost:9080/system/properties` URL retrieves the system property information for a specific host. In this case, `localhost` is a specific host name.

* The `http://localhost:9080/inventory/systems/localhost` URL retrieves the system property information for `localhost` by invoking the `http://localhost:9080/system/properties` microservice.

* Get your internal IP address first, then visit the `http://localhost:9080/inventory/systems/+<your_hostname>+` URL by replacing `<your_hostname>` with your IP address. You will see the same system property information, but the process of getting this information is actually implemented differently.

When you are done checking out the application, stop the Open Liberty server:

```
mvn liberty:stop-server
```

Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Writing the RESTful client interface
// =================================================================================================
== Writing the RESTful client interface

The MicroProfile Rest Client API are added as a dependency to your `pom.xml` file. Look for the dependency with the `microprofile-rest-client-api` artifact ID.
This dependency provides the library that is required to implement the MicroProfile Rest Client interface.

The `mpRestClient-1.0` feature is also enabled in the `src/main/liberty/config/server.xml` file. This feature allows you to use the MicroProfile Rest Client to invoke RESTful microservices with template interfaces.

The code for the `system` service in the `src/main/java/io/openliberty/guides/system` directory is provided for you. It simulates a remote RESTful service that
the `inventory` service tries to invoke.

Now, create a RESTful client interface for the `system` service. To do so, create the `SystemClient` class in the `src/main/java/io/openliberty/guides/inventory/client/SystemClient.java` file:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=client]
----

The service automatically builds and generates an implementation for the `SystemClient` interface, because the JAX-RS annotations in the interface tell the RESTful service
what to do. You don't have to worry about all of the boilerplate code, such as setting up a client class, connecting to the remote server, or invoking the right URI with the right parameters.

When the `getProperties()` method gets invoked, the `SystemClient` instance sends a GET request to the endpoint at `<baseUrl>/properties`.

The `@Dependent` annotation tells the service that the scope of the interface is dependent on the class that they get injected into.

The `@RegisterRestClient` annotation registers the interface as a RESTful client.

The `@RegisterProvider` annotation tells the framework to register provider classes to be used when invoking the interface; you can add as many providers as necessary.
In the `SystemClient`, you add a response exception mapper as a provider to map the `404 NOT FOUND` response code with the `UnknownUrlException` exception.

// =================================================================================================
// Handling exceptions through ResponseExceptionMappers
// =================================================================================================
=== Handling exceptions through ResponseExceptionMappers

In the `SystemClient` interface, the `getProperties()` method might throw an `UnknownUrlException` exception if the response from the `system` service is `404 NOT FOUND`, and `@RegisterProvider(UnknownUrlExceptionMapper.class)` registers the response exception mapper.
Implement the actual exception class and the mapper class to see how this mechanism works.

Create an `UnknownUrlException` exception class in the `src/main/java/io/openliberty/guides/inventory/client/UnknownUrlException.java` file:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/UnknownUrlException.java[tags=exception]
----

Now, link the `UnknownUrlException` class with the corresponding response code through a `ResponseExceptionMapper` mapper class.
Create an `UnknownUrlExceptionMapper` mapper class in the `src/main/java/io/openliberty/guides/inventory/client/UnknownUrlExceptionMapper.java` file:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/UnknownUrlExceptionMapper.java[tags=mapper]
----

The `handles()` method inspects the HTTP response code to determine if an exception should be thrown for the specific response, and the `toThrowable()` method returns the mapped exception.

// =================================================================================================
// Injecting the client with dependency injection
// =================================================================================================
== Injecting the client with dependency injection

Now, instantiate the `SystemClient` interface and use it in the `inventory` service. If you only want to connect with the default host name, it is easy to instantiate the `SystemClient` by using CDI annotations.

First, configure the default base URL of the `SystemClient` instance by using MicroProfile Config. The feature has been enabled for you in both `server.xml` and `pom.xml` files.
Create a configuration file `src/main/webapp/META-INF/microprofile-config.properties` and add a config property `<fullyQualifiedInterfaceName>/mp-rest/url`, which in this case is `io.openliberty.guides.inventory.client.SystemClient/mp-rest/url`.
Configure this property to the default `http://localhost:9080/system` base URL:

[source, java, indent=0]
----
include::finish/src/main/webapp/META-INF/microprofile-config.properties[tags=config]
----

This configuration will be automatically picked up by the MicroProfile Config API.

Revisit the `SystemClient` interface from the previous section:
[source, java, indent=0, role="no_copy"]
----
include::finish/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java[tags=annotations]
----
The `@Dependent` and `@RegisterRestClient` annotations imply that the interface is manageable through context and dependency injection.

Create the `InventoryManager` class in the `src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:
[source, java, indent=0]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=manager]
----

`@Inject` and `@RestClient` annotations inject an instance of the `SystemClient` called `defaultRestClient` to the `InventoryManager` class.
Since `InventoryManager` class is another CDI managed object and CDI requires one to inject the `SystemClient`, you add the client here.

If the parameter `hostname` is `localhost`, the service runs the `getPropertiesWithDefaultHostName()` helper function to fetch system properties.
It invokes the `system` service by calling the `defaultRestClient.getProperties()` method.

// =================================================================================================
// Building the client with RestClientBuilder
// =================================================================================================
== Building the client with RestClientBuilder

The `inventory` service might also provide a different host name rather than the default `localhost`. Set the host name as a variable and build the client by using the `RestClientBuilder` method.

Look at the `getPropertiesWithGivenHostName()` method in the `src/main/java/io/openliberty/guides/inventory/InventoryManager.java` file:
[source, java, indent=0, role="no_copy"]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryManager.java[tags=builder]
----

The host name is provided as a parameter. This method first assembles the base URL consisted of the new host name, then, instantiates a `RestClientBuilder` builder with the new URL, registers the response exception mapper, and builds the `SystemClient` instance.

Similarly, call the `customRestClient.getProperties()` method to invoke the `system` service.

// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Once the server is running, try to fetch your system properties by two approaches:

1. Visit the `http://localhost:9080/inventory/systems/localhost` URL. It retrieves the system property information for `localhost` by invoking the `http://localhost:9080/system/properties` service.

2. Get your internal IP address first. Then, visit the `http://localhost:9080/inventory/systems/+<your_hostname>+` URL by replacing `<your_hostname>` with your IP address. It retrieves your system properties by invoking the `http://<your_hostname>:9080/system/properties` service.

include::{common-includes}/mvnpackage.adoc[]


// =================================================================================================
// Testing the application
// =================================================================================================

== Testing the application

Create a `RestClientTest` test class in the `src/test/java/it/io/openliberty/guides/client/RestClientTest.java` file:

[source, java, indent=0]
----
include::finish/src/test/java/it/io/openliberty/guides/client/RestClientTest.java[tags=testClass]
----

Each test case tests one of the methods for instantiating a RESTful client.

The `testDefaultLocalhost()` test fetches and compares system properties from the `http://localhost:9080/inventory/systems/localhost` URL.

The `testRestClientBuilder()` test first gets your IP address. Then, use your IP address as the host name to fetch your system properties and compare them.

In addition, a few endpoint tests are provided for you to test the basic functionality of the `inventory` and `system` services. If a test failure occurs, you might have introduced a bug into the code.

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.377 sec - in it.io.openliberty.guides.system.SystemEndpointTest
Running it.io.openliberty.guides.inventory.InventoryEndpointTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.379 sec - in it.io.openliberty.guides.inventory.InventoryEndpointTest
Running it.io.openliberty.guides.client.RestClientTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.121 sec - in it.io.openliberty.guides.client.RestClientTest

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, change the base URL in the configuration file, so that when the `inventory` service tries to access the invalid URL, a `404 NOT FOUND` exception is thrown.
Re-run the Maven build. You will see a test failure occur. Re-start the liberty server and visit `http://localhost:9080/inventory/systems/localhost`, you will see the error message `ERROR: Unknown hostname or the system service may not be running on localhost`.

== Great work! You're done!

You just built and tested a MicroProfile application with MicroProfile Rest Client and Open Liberty.

Feel free to try one of the related guides. They demonstrate more technologies that you can learn and
expand on what you built in this guide.

include::{common-includes}/finish.adoc[]
